/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCol: typeof import('tdesign-vue-next')['Col']
  const TProgress: typeof import('tdesign-vue-next')['Progress']
  const TRow: typeof import('tdesign-vue-next')['Row']
  const TSlider: typeof import('tdesign-vue-next')['Slider']
  const TUpload: typeof import('tdesign-vue-next')['Upload']
}